version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: books_postgres_c
    environment:
      POSTGRES_USER: 'book_admin'
      POSTGRES_PASSWORD: 'abc'
      POSTGRES_DB: 'books_db'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: books_client_c
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: books_server_c
    environment:
      POSTGRES_USER: 'book_admin'
      POSTGRES_PASSWORD: 'abc'
      POSTGRES_DB: 'books_db'
      POSTGRES_HOST: 'postgres' # Use the service name as the host
      POSTGRES_PORT: 5432
    ports:
      - '2000:2000'
    depends_on:
      - postgres
    restart: always # Add this line
    # Remove or comment out the volume mount
    # volumes:
    #   - ./server:/usr/src/app

volumes:
  postgres_data:
